<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2021-11-06 09:30:22 --> 404 Page Not Found: Faviconico/index
ERROR - 2021-11-06 09:30:43 --> Query error: Unknown column 'access_date' in 'field list' - Invalid query: INSERT INTO `twillio_logs` (`ipaddress`, `logtype`, `access_date`, `phone`, `code`) VALUES ('72.216.83.133', 'Subscription Access', '2021-11-06 09:30:43', '+14808231000', '211057')
ERROR - 2021-11-06 15:56:11 --> 404 Page Not Found: Faviconico/index
ERROR - 2021-11-06 15:56:11 --> 404 Page Not Found: Apple-touch-iconpng/index
ERROR - 2021-11-06 15:56:11 --> 404 Page Not Found: Faviconico/index
ERROR - 2021-11-06 15:56:19 --> Query error: Unknown column 'access_date' in 'field list' - Invalid query: INSERT INTO `twillio_logs` (`ipaddress`, `logtype`, `access_date`, `phone`, `code`) VALUES ('68.80.138.229', 'Card Image Access', '2021-11-06 15:56:19', '+16106747282', '411808')
ERROR - 2021-11-06 15:56:29 --> 404 Page Not Found: Apple-touch-iconpng/index
ERROR - 2021-11-06 15:56:29 --> 404 Page Not Found: Faviconico/index
ERROR - 2021-11-06 16:40:23 --> 404 Page Not Found: Faviconico/index
ERROR - 2021-11-06 16:40:57 --> 404 Page Not Found: Faviconico/index
ERROR - 2021-11-06 16:41:32 --> Query error: Unknown column 'access_date' in 'field list' - Invalid query: INSERT INTO `twillio_logs` (`ipaddress`, `logtype`, `access_date`, `phone`, `code`) VALUES ('67.143.193.19', 'Card Image Access', '2021-11-06 16:41:32', '+12054549837', '596756')
ERROR - 2021-11-06 16:41:48 --> Query error: Unknown column 'access_date' in 'field list' - Invalid query: INSERT INTO `twillio_logs` (`ipaddress`, `logtype`, `access_date`, `phone`, `code`) VALUES ('67.143.193.19', 'Card Image Access', '2021-11-06 16:41:48', '+12057719466', '469672')
ERROR - 2021-11-06 16:46:22 --> 404 Page Not Found: Faviconico/index
ERROR - 2021-11-06 16:46:37 --> Query error: Unknown column 'access_date' in 'field list' - Invalid query: INSERT INTO `twillio_logs` (`ipaddress`, `logtype`, `access_date`, `phone`, `code`) VALUES ('64.83.161.229', 'Card Image Access', '2021-11-06 16:46:37', '+12053005694', '355628')
ERROR - 2021-11-06 16:48:20 --> Query error: Unknown column 'access_date' in 'field list' - Invalid query: INSERT INTO `twillio_logs` (`ipaddress`, `logtype`, `access_date`, `phone`, `code`) VALUES ('64.83.161.229', 'Card Image Access', '2021-11-06 16:48:20', '+12053005694', '268463')
ERROR - 2021-11-06 16:53:49 --> Query error: Unknown column 'access_date' in 'field list' - Invalid query: INSERT INTO `twillio_logs` (`ipaddress`, `logtype`, `access_date`, `phone`, `code`) VALUES ('64.83.161.229', 'Card Image Access', '2021-11-06 16:53:49', '+12053005694', '671523')
ERROR - 2021-11-06 17:01:42 --> Query error: Unknown column 'access_date' in 'field list' - Invalid query: INSERT INTO `twillio_logs` (`ipaddress`, `logtype`, `access_date`, `phone`, `code`) VALUES ('107.77.234.53', 'Card Image Access', '2021-11-06 17:01:42', '+12053005694', '874051')
ERROR - 2021-11-06 17:04:07 --> Query error: Unknown column 'access_date' in 'field list' - Invalid query: INSERT INTO `twillio_logs` (`ipaddress`, `logtype`, `access_date`, `phone`, `code`) VALUES ('107.77.234.53', 'Card Image Access', '2021-11-06 17:04:07', '+12053005694', '451127')
ERROR - 2021-11-06 19:45:10 --> 404 Page Not Found: Faviconico/index
ERROR - 2021-11-06 21:44:02 --> 404 Page Not Found: Faviconico/index
ERROR - 2021-11-06 21:44:12 --> Query error: Unknown column 'access_date' in 'field list' - Invalid query: INSERT INTO `twillio_logs` (`ipaddress`, `logtype`, `access_date`, `phone`, `code`) VALUES ('75.137.68.28', 'Card Image Access', '2021-11-06 21:44:12', '+12053005692', '567994')
ERROR - 2021-11-06 21:46:33 --> Query error: Unknown column 'access_date' in 'field list' - Invalid query: INSERT INTO `twillio_logs` (`ipaddress`, `logtype`, `access_date`, `phone`, `code`) VALUES ('75.137.68.28', 'Card Image Access', '2021-11-06 21:46:33', '+12053005692', '181191')
ERROR - 2021-11-06 21:46:37 --> Query error: Unknown column 'access_date' in 'field list' - Invalid query: INSERT INTO `twillio_logs` (`ipaddress`, `logtype`, `access_date`, `phone`, `code`) VALUES ('71.150.122.34', 'Subscription Access', '2021-11-06 21:46:37', '+12055340349', '122885')
ERROR - 2021-11-06 21:48:01 --> Query error: Unknown column 'access_date' in 'field list' - Invalid query: INSERT INTO `twillio_logs` (`ipaddress`, `logtype`, `access_date`, `phone`, `code`) VALUES ('71.150.122.34', 'Card Image Access', '2021-11-06 21:48:01', '+12055340349', '892102')
